
# SEO settings
title: "chaos"
title2: "ii" # default: ""
# description: "Just another minimalist Jekyll theme that focuses on technical writing."
description: "Tech blog"
keywords: "blog,长风逝君怀,前端,chaos,Front-end,liyv1314"
url: http://liyv1314.github.io/blog # site url
baseurl: "/blog" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/liyv1314/blog
disqus_shortname: "chaosii"
twitter_username: "liyv1314"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "chaos_li"
  job      : "Front-end Engineer"
  bio      : "Chaos is the truth of the world!"
  thumb    : /images/author.jpg
  email    : liyv1314@sina.com
  url      : http://liyv1314.github.io
  github   : http://github.com/liyv1314
  twitter  : http://twitter.com/liyv1314
  facebook : 
  linkedin : 

# social settings
og_locale: "en_US"
twitter_card: ""
twitter_site: "@liyv1314"


gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
